name: CheckPRLinks
on:
  pull_request:
    branches: [main, next-release/main]
    types: [opened, synchronize]
jobs:
  CheckPRLinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0 https://github.com/actions/checkout/commit/f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Setup Node.js 16.x
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0 https://github.com/actions/setup-node/commit/e33196f7422957bea03ed53f6fbb155025ffc7b8
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn
      - name: Run Build
        run: yarn build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Serve Files
        uses: Eun/http-server-action@6befadcf3bf8d9a4fcc563c1ffba0e59f188a1e5 # v1.0.10 https://github.com/Eun/http-server-action/commit/6befadcf3bf8d9a4fcc563c1ffba0e59f188a1e5
        with:
          directory: ${{ vars.BUILD_DIR }}
          port: 3000
          no-cache: false
          index-files: |
            ["index.html", "index.htm"]
          allowed-methods: |
            ["GET", "HEAD"]
          content-types: |
            {
              "appcache": "text/cache-manifest",
              "css": "text/css",
              "gif": "image/gif",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "txt": "text/plain",
              "xml": "text/xml"
            }
          log: 'log.txt'
          logTime: 'true'
      - name: Run Link Checker
        id: checkLinks
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1 https://github.com/actions/github-script/commit/d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          result-encoding: string
          script: |
            const { checkDevLinks } = require('./tasks/link-checker.js');
            return await checkDevLinks();
      - name: Fail if broken links have been found
        if: ${{ steps.checkLinks.outputs.result }}
        run: exit 1
